#!/usr/bin/env ruby
require_relative "lib/bbcode_progress"
require_relative "lib/config"
require_relative "lib/phpbb"
include SigUpdater

# Order of precedence: command-line argument, then config file, then env var.
config = SigUpdater::Config.get_info(nil)
puts "Logging into #{config.site} as user '#{config.username}'..."

forum = PhpBB.new(config.site, config.username, config.password)
old_sig = forum.signature
new_sig = BBCodeProgress.update(old_sig, ARGV)

puts "\nOLD SIG:\n\n#{old_sig}"
if old_sig == new_sig
  puts "\nNo changes to sig."
  exit
end

forum.signature = new_sig
puts "\nNEW SIG:\n\n#{new_sig}"

